version: "3.9"

services:
  locacao_ti:
    build: .
    ports:
      - 8080:8080
    networks:
      - locacao_net
    
  locacao_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      .env
    networks:
      - locacao_net

networks:
  locacao_net:
    driver: bridge
